### ISSUE TITLE
$ pip install https://s3-ap-southeast-1.amazonaws.com/posit-speedgo/tensorflow_posit-1.11.0.0.0.1.dev1-cp36-cp36m-linux_x86_64.whl

### ISSUE THREAD

**Issue by Amithvassit** [RaulMurillo/deep-pensieve#3]
Not able to get this installed , 
Can you please specify the requirements of the machine and versions of the software

**Comment by RaulMurillo** [comment]
Which is exactly the error you get at installation?
Running the following commands in order gets to a successful installation on an Ubuntu 18.04 system:
``` bash
pip install numpy-posit
pip install requests
pip install https://s3-ap-southeast-1.amazonaws.com/posit-speedgo/tensorflow_posit-1.11.0.0.0.1.dev1-cp36-cp36m-linux_x86_64.whl
pip install softposit
```

If you get an error with the TensorFlow version on your system, you can check with the different wheels that are found in https://github.com/xman/tensorflow/wiki

**Comment by Amithvassit** [comment]
which python and tensorflow version is suggested ?

**Comment by RaulMurillo** [comment]
Python >= 3.6
A modified version of TensorFlow is installed with the wheel file and pip command mentioned in the issue title. If you have TensorFlow previously installed, I guess some problems will raise, since it is not a different-named package such as numpy-posit.
I suggest installing these packages in a virtual environment.
